### PR TITLE
Restore the correct initial selection in media manager.

### PR DESCRIPTION
**Pull request by Kelderic**
Restore the correct initial selection in media manager.

### CODE REVIEW

**Comment by Kelderic** [comment]
@Monter, here should be fixed initial selection.

**Comment by ronalfy** [comment]
This looks good and tested. @Monter if you have time, can you confirm, otherwise I'll merge this evening.

**Comment by Monter** [comment]
I tried the latest Keldric version and commented here: https://github.com/ronalfy/user-profile-picture/commit/6be034db1678ebcc9e4649e254199ba52e70493a#commitcomment-18832393

At the moment I got back to ["my" version](https://github.com/Monter/user-profile-picture/commit/a08e9b414953f661eb21e5e66912ba3a0db7a08a) and it works the way I expect.

**Comment by Kelderic** [comment]
@Monter, what do you expect to happen if you click to open Media Manager when the user still has the default image?

**Comment by ronalfy** [comment]
I'll put together something real quick in another branch.

**Pull request closed without merging**
