### PR TITLE
Visual Bugfixes and Nonexistant Default Image Fix

### PR DESCRIPTION
**Pull request by Kelderic**
Per discussion in support thread here:

https://wordpress.org/support/topic/visual-bug-and-fix?replies=7

(This is my first attempt at forking and submitting a pull request, so please let me know if I screwed anything up)

### CODE REVIEW

**Comment by ronalfy** [comment]
Thanks for the PR! I'll take a look at it this evening.

**Comment by ronalfy** [comment]
@Monter @Kelderic All issues should be resolved in this PR. https://github.com/ronalfy/user-profile-picture/pull/6

**Comment by Kelderic** [comment]
Tested and looks good. Also I need to apologize, I realized another plugin was causing some interference. With it disabled, problems are greatly reduced.

The only thing I see with #6 is that the selected image isn't moved to first spot, which was @Monter's concern:

pr6

**Comment by ronalfy** [comment]
I'm okay with that. It works that way for regular post featured images also.

**Comment by Kelderic** [comment]
True. Which then makes this the exact same in behavior to my second pull request. We are just using the fact that using the predefined Featured Image state already does the initial selection for us. The media uploader JS is one of the most complicated pieces of JS that I've ever worked with. I gave up trying to find the featured image controller definition, to figure out how it is doing the initial selection.

**Comment by Monter** [comment]
Hello again,
There is still something wrong. When you select an image you uploaded a long time ago in the gallery much lower, indicating the image no longer works (pointing to the file until the profile/settings are saved).

**Pull request merged**
